-- Galeria realizacji — konfiguracja Supabase
-- Do wklejenia w SQL Editor projektu (tizciyilckwicjexlzgr).
-- Skrypt można uruchomić ponownie, nic nie nadpisze istniejących danych.

-- ── Tabela ───────────────────────────────────────────────────────────────────
create table if not exists public.gallery (
    id           bigint generated by default as identity primary key,
    category     text not null,
    filename     text,
    url          text not null,
    storage_path text,
    created_at   timestamptz not null default now()
);

-- Kolumny dochodzą osobno, bo tabela powstała wcześniej w węższej postaci.
alter table public.gallery add column if not exists storage_path text;
alter table public.gallery add column if not exists created_at timestamptz not null default now();

alter table public.gallery
    drop constraint if exists gallery_category_check;
alter table public.gallery
    add constraint gallery_category_check
    check (category in ('kuchnie', 'szafy', 'garderoby', 'lazienki'));

create index if not exists gallery_category_created_idx
    on public.gallery (category, created_at desc);

-- ── Uprawnienia do tabeli ────────────────────────────────────────────────────
-- Zapis idzie wyłącznie przez funkcje serwerowe (klucz service_role), więc
-- przeglądarka może tu tylko czytać.
alter table public.gallery enable row level security;

drop policy if exists "gallery_public_read" on public.gallery;
create policy "gallery_public_read"
    on public.gallery for select
    using (true);

-- ── Miejsce na pliki ─────────────────────────────────────────────────────────
-- Bucket musi być publiczny, bo strona wyświetla zdjęcia wprost z jego adresu.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'gallery',
    'gallery',
    true,
    10485760,                                              -- 10 MB na plik
    array['image/jpeg', 'image/png', 'image/webp', 'image/heic']
)
on conflict (id) do update
set public             = true,
    file_size_limit    = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "gallery_files_public_read" on storage.objects;
create policy "gallery_files_public_read"
    on storage.objects for select
    using (bucket_id = 'gallery');
